export const LDRStates = Object.freeze({
  INITIAL: 'INITIAL',
  INIT_BROADCAST_CHANNELS: 'INIT_BROADCAST_CHANNELS',
  CHECK_WORKERS_DEFINED: 'CHECK_WORKERS_DEFINED',
  LOAD_WORKER: 'LOAD_WORKERS',
  CHECK_ALL_WORKERS_LOADED: 'CHECK_ALL_WORKERS_LOADED',
  CONFIG_WORKER: 'CONFIG_WORKER', 
  CHECK_ALL_WORKERS_CONFIGURED: 'CHECK_ALL_WORKERS_CONFIGURED',
  START_WORKER: 'START_WORKER',
  CHECK_ALL_WORKERS_STARTED: 'CHECK_ALL_WORKERS_STARTED',
  ER: 'ER',
  OK: 'OK',
});