export const LDRSignals = Object.freeze({
  BROADCAST_CHANNELS_INITIALIZED: 'BROADCAST_CHANNELS_INITIALIZED',
  WORKER_LOADED: 'WORKER_LOADED',
  WORKER_CONFIGURED: 'WORKER_CONFIGURED',
  WORKER_STARTED: 'WORKER_STARTED',
});